// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyTrack.Data;

#nullable disable

namespace StudyTrack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910033413_EsquemaSimplificado")]
    partial class EsquemaSimplificado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyTrack.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActividadPadreId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GeneradaAutomaticamente")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActividadPadreId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("StudyTrack.Models.Actividad", b =>
                {
                    b.HasOne("StudyTrack.Models.Actividad", "ActividadPadre")
                        .WithMany("ActividadesHijas")
                        .HasForeignKey("ActividadPadreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActividadPadre");
                });

            modelBuilder.Entity("StudyTrack.Models.Actividad", b =>
                {
                    b.Navigation("ActividadesHijas");
                });
#pragma warning restore 612, 618
        }
    }
}
