// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyTrack.Api.Repositories;

#nullable disable

namespace StudyTrack.Api.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913222350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyTrack.Api.Domain.Actividad", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActividadPadreId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GeneradaAutomaticamente")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadPadreId");

                    b.HasIndex("UserId", "Titulo", "FechaFin")
                        .IsUnique();

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("StudyTrack.Api.Domain.Actividad", b =>
                {
                    b.HasOne("StudyTrack.Api.Domain.Actividad", "ActividadPadre")
                        .WithMany("ActividadesHijas")
                        .HasForeignKey("ActividadPadreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActividadPadre");
                });

            modelBuilder.Entity("StudyTrack.Api.Domain.Actividad", b =>
                {
                    b.Navigation("ActividadesHijas");
                });
#pragma warning restore 612, 618
        }
    }
}
